replicaCount: 1

image:
  repository: 279663581923.dkr.ecr.us-west-1.amazonaws.com/checkout-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8084

env:
  CART_SERVICE_URL: "http://cart-service-release-cart-service:8083/api/cart"

envFrom:
  - secretRef:
      name: mongodb-secret
  - secretRef:
      name: jwt-secret
  - secretRef:
      name: rabbitmq-secret
