apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # Only include the ports section if the service is enabled in values.yaml
          {{- if .Values.service.enabled }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- end }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}