services:
  # --- Backend API Services ---
  user-service:
    build: ./services/user-service
    ports: ["8081:8081"]
    volumes: ["./services/user-service:/app"]
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}

  catalog-service:
    build: ./services/catalog-service
    ports: ["8082:8082"]
    volumes: ["./services/catalog-service:/app"]
    environment:
      - MONGO_URI=${MONGO_URI}

  cart-service:
    build: ./services/cart-service
    ports: ["8083:8083"]
    volumes: ["./services/cart-service:/app"]
    environment:
      - REDIS_ADDR=redis:6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis

  checkout-service:
    build: ./services/checkout-service
    ports: ["8084:8084"]
    volumes: ["./services/checkout-service:/app"]
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      rabbitmq:
        condition: service_healthy

  # --- Backend Worker Services ---
  notification-service:
    build: ./services/notification-service
    volumes: ["./services/notification-service:/app"]
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy

  payment-service:
    build: ./services/payment-service
    volumes:
      - ./services/payment-service:/app
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy

  # --- Infrastructure ---
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports: ["5672:5672", "15672:15672"]
    healthcheck: # Add this healthcheck block
      test: ["CMD", "rabbitmq-diagnostics", "check_running", "-q"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  # --- Frontend Service ---
  frontend:
    build: ./frontend
    ports: ["5173:5173"]
    volumes: ["./frontend:/app", "/app/node_modules"]
    depends_on:
      - user-service
      - catalog-service
      - cart-service
      - checkout-service
