# ---- Stage 1: The Builder ----

    FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /catalog-service-binary .

# ---- Stage 2: The Final Image ----
FROM scratch

COPY --from=builder /catalog-service-binary /catalog-service-binary

EXPOSE 8082

CMD ["/catalog-service-binary"]