# Config file for Air live-reloader
root = "."
tmp_dir = "tmp"

[build]
# Command to build your app
cmd = "go build -o ./tmp/main ."
# Binary to execute
bin = "./tmp/main"
# Watch these file extensions
include_ext = ["go", "tpl", "tmpl", "html"]
# Ignore these directories
exclude_dir = ["assets", "tmp", "vendor"]
# Log name for the build process
log = "air_build.log"

[log]
# Show log time
time = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true