# ---- Stage 1: The Builder ----

    FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /notification-service-binary .

# ---- Stage 2: The Final Image ----
FROM scratch

COPY --from=builder /notification-service-binary /notification-service-binary

EXPOSE 8082

CMD ["/notification-service-binary"]