replicaCount: 1

image:
  repository: 279663581923.dkr.ecr.us-west-1.amazonaws.com/cart-service
  pullPolicy: IfNotPresent
  # The tag is intentionally left blank. We override it with --set
  tag: "latest"

service:
  type: ClusterIP
  port: 8083

env:
  CATALOG_SERVICE_URL: "http://catalog-service-release-catalog-service:8082/api/products/batch-get"

envFrom:
  - secretRef:
      name: redis-secret
  - secretRef:
      name: jwt-secret
