replicaCount: 1

image:
  repository: 279663581923.dkr.ecr.us-west-1.amazonaws.com/user-service
  pullPolicy: IfNotPresent
  # The tag is intentionally left blank. We override it with --set
  tag: ""

service:
  type: ClusterIP
  port: 8081

envFrom:
  - secretRef:
      name: mongodb-secret
  - secretRef:
      name: jwt-secret
